### PR TITLE
[Fix #112] Fixes issue with obsolete Rubocop changes

### LINKED ISSUE #112: Obsolete Rubocop syntax prevents code linting
There are some minor  Rubocop style issues around which prevents the code from being checked for quality. See below for more details on this issue.

```
[jonesagyemang:~/Projects/starred_projects/http-2] master+ 2h26m7s ± rubocop
.rubocop.yml: Style/CaseIndentation has the wrong namespace - should be Layout
.rubocop.yml: Style/IndentHash has the wrong namespace - should be Layout
.rubocop.yml: Style/SpaceAroundOperators has the wrong namespace - should be Layout
.rubocop.yml: Style/ExtraSpacing has the wrong namespace - should be Layout
.rubocop_todo.yml: Style/IndentArray has the wrong namespace - should be Layout
.rubocop_todo.yml: Style/MultilineArrayBraceLayout has the wrong namespace - should be Layout
.rubocop_todo.yml: Style/MultilineHashBraceLayout has the wrong namespace - should be Layout
Error: obsolete parameter IndentWhenRelativeTo (for Layout/CaseIndentation) found in .rubocop.yml
`IndentWhenRelativeTo` has been renamed to `EnforcedStyle`
obsolete parameter AlignWith (for Lint/EndAlignment) found in .rubocop.yml
`AlignWith` has been renamed to `EnforcedStyleAlignWith`
```

### PR DESCRIPTION
**Pull request by Tr4pSt3R**
Fixes issue reported here: https://github.com/igrigorik/http-2/issues/112

---
This change is [Reviewable](https://reviewable.io/reviews/igrigorik/http-2/113)

### CODE REVIEW

**Comment by igrigorik** [comment]
From the build logs:

> Warning: unrecognized parameter Lint/EndAlignment:EnforcedStyleAlignWith found in /home/travis/build/igrigorik/http-2/.rubocop.yml
> Warning: unrecognized parameter Style/CaseIndentation:EnforcedStyleIndentWhenRelativeTo found in /home/travis/build/igrigorik/http-2/.rubocop.yml

Do we need to rev the version of rubocop as well? 

Also, I'm seeing rubocop failures in the build now: https://travis-ci.org/igrigorik/http-2/jobs/327636106 — are those expected with this update?

**Comment by Tr4pSt3R** [comment]
@igrigorik I'm planning a separate PR to deal with the actual errors. The plan for this one is to keep the PRs as small as possible.

**Comment by igrigorik** [comment]
@Tr4pSt3R small is good, but in this case we'll break the build, which can affect others working on the code, etc. Can we also get the fix integrated here? :)

**Comment by Tr4pSt3R** [comment]
@igrigorik yeah, I can do that 👍

**Comment by igrigorik** [comment]
@Tr4pSt3R any luck on your end?

**Comment by Tr4pSt3R** [comment]
@igrigorik there are some issues which are dependant on some PRs from Rubocop's end being pushed through. I am monitoring the situation.

**Comment by igrigorik** [comment]
@Tr4pSt3R cool, thanks for the update!

**Comment by igrigorik** [comment]
@Tr4pSt3R any updates? :-)

**Comment by Tr4pSt3R** [comment]
@igrigorik I have been away on vacations for about a month

**Comment by igrigorik** [comment]
@Tr4pSt3R nice! No rush, just wanted to check-in..

**Comment by ioquatix** [comment]
@Tr4pSt3R Can you please provide an update? Will you have time to complete this PR?

**Comment by Tr4pSt3R** [comment]
@ioquatix I will find time to look into this again and update you accordingly

**Comment by ioquatix** [comment]
We have updated rubocop. If you have further improvements, please create a new PR. Thanks so much for your past efforts and attention.

**Pull request closed without merging**
