### PR TITLE
Fixes missing frame[:flags] when data frames are split

### PR DESCRIPTION
**Pull request by tbetbetbe**
Also fixes

a similar issue in flow_buffer#send_data

### CODE REVIEW

**Comment by igrigorik** [comment]
When does this become an error? Do you have an error test case? Instead of doing the check should we guarantee that :flags is is always initialized?

**Comment by tbetbetbe** [comment]
> When does this become an error ?
when trying to determine the transition for a DATA frame that has no flags.  E.g, when sending multiple DATA frames, any frame that is not the final one

> Do you have an error test case ?
I just added one

> Instead of doing the check should we guarantee the :flags is always initialized

That might be better
```sh
$ grep :flags -R lib | wc -l  # check for number of sites where :flags is used
   21
```
I see 21 sites where :flags is used, making sure flags is initialized would ensure that none of these are affected.  I can change the PR to do that if you like?

**Comment by tbetbetbe** [comment]
The test case can be improved - maybe it should demonstrate that a parsed frame can result in a frame hash where :flags is nil, the fix would be to modify the parsing code to ensure this does not happen.

**Comment by igrigorik** [comment]
> The test case can be improved - maybe it should demonstrate that a parsed frame can result in a frame hash where :flags is nil, the fix would be to modify the parsing code to ensure this does not happen.

The fact that there are 21 spots where this (flags == nil) is a potential issue is a strong argument for above approach. Let's do it :)

**Comment by tbetbetbe** [comment]
Done:  PTAL

**Comment by igrigorik** [comment]
:+1: great stuff!

**Pull request merged**
