### PR TITLE
update max frame size on receiving SETTINGS frame from peer

### PR DESCRIPTION
**Pull request by sankarcheppali**
Currently the framer max_frame_size is not being updated as reported in [151](https://github.com/igrigorik/http-2/issues/151).  This PR tries fix that

### CODE REVIEW

**Review by igrigorik — COMMENTED** [review]
Thank you for the contribution!  Overall, looks great. 

Q: should there be a min/max boundary check?

**Comment by sankarcheppali** [comment]
> Thank you for the contribution! Overall, looks great.
> 
> Q: should there be a min/max boundary check?

Cool. We are already doing a check with validate_settings before accepting the remote settings. We could add one more check in framer if you feel that is required

**Comment by igrigorik** [comment]
Ah, good point! No, should be good. Ready to merge, or do you have anything else pending?

**Comment by sankarcheppali** [comment]
We are good to merge 👍

**Pull request merged**
