### PR TITLE
[DO NOT MERGE] RuboCop regexp

### PR DESCRIPTION
**Pull request by tamird**
@igrigorik @madp the last 3 commits here should address your concerns from #19. I'll update this when a new release of RuboCop is cut. /cc @bbatsov any plans to release a new version of RuboCop?

### CODE REVIEW

**Comment by bbatsov** [comment]
Excellent timing! I plan to release the new RuboCop tomorrow.

**Comment by igrigorik** [comment]
@tamird this looks like a replacement pull for #19? Should we close that one then?

**Comment by tamird** [comment]
Nah, this is just a staging PR - let's merge #19 and then we'll merge this one a few days from now (and it will only contain the last 3 commits)

**Comment by igrigorik** [comment]
Wouldn't that result in unnecessary code churn? A clean history makes tracing a lot easier.. been burned by such things in the past, and its not fun to deal with.

**Comment by tamird** [comment]
@igrigorik eh..okay, I'll close this and we can hold off merging #19 until tomorrow when the new rubocop lands.

**Pull request closed without merging**
