### PR TITLE
(WIP) h2c Upgrade support

### PR DESCRIPTION
**Pull request by igrigorik**
Needs more testing and a few sanity checks, but basic support should be there.

_p.s. credit to @kenichi for bulk of the work here! See: https://github.com/igrigorik/http-2/commit/376d4433b1b3e738ed8e827b99c7cfe43dfa50f6_

### CODE REVIEW

**Comment by kenichi** [comment]
@igrigorik i've been super swamped but do plan on looking at this soon!

**Comment by igrigorik** [comment]
@kenichi no rush and thanks.. I have a few small cleanup things to do on the pull, but otherwise I think it's mostly there.

**Comment by kenichi** [comment]
@igrigorik almost a year later! 😳  i finally got around to reimplementing this on reel - *still a WIP* - but the `.upgrade` method sure is handy. 👍 

https://github.com/celluloid/reel/compare/master...kenichi:h2

**Comment by georgeu2000** [comment]
LOL, I spent all weekend trying to figure this out.

**Comment by kenichi** [comment]
@georgeu2000 uh oh sorry - anything i can (try to) help with?

**Comment by georgeu2000** [comment]
@kenichi - Does example/upgrade_server work with any browser for you? Right now I am figuring out where `http_parser` comes from.

**Comment by kenichi** [comment]
@georgeu2000 browsers only like h2 [over TLS](http://caniuse.com/#feat=http2) so i've been testing with [nghttp2](https://github.com/nghttp2/nghttp2). i think if you build curl with h2 support it will do upgrades too.

```
utwig:http-2 $ nghttp -vu http://127.0.0.1:8080/                                                                                                                                                    [29/32]
[  0.003] Connected
[  0.004] HTTP Upgrade request
GET / HTTP/1.1
host: 127.0.0.1:8080
connection: Upgrade, HTTP2-Settings
upgrade: h2c
http2-settings: AAMAAABkAAQAAP__
accept: */*
user-agent: nghttp2/1.16.0-DEV


[  0.004] HTTP Upgrade response
HTTP/1.1 101 Switching Protocols
Connection: Upgrade
Upgrade: h2c


[  0.004] HTTP Upgrade success
[  0.005] recv SETTINGS frame <length=6, flags=0x00, stream_id=0>
          (niv=1)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
...
```

**Comment by igrigorik** [comment]
@georgeu2000 h2c is not supported by any popular browsers: https://hpbn.co/transport-layer-security-tls/#proxies-intermediaries-tls-and-new-protocols-on-the-web. As @kenichi suggested, you'll have to use an alternative client to test h2c.

**Comment by georgeu2000** [comment]
Thank you for all the helpful info. I want to run h2 locally over TLS using http-2 gem. 

I set up TLS using a Self Signed Certificate, and I \*think* it works:
```
curl -vk --cert lib/keys/server.pem --key lib/keys/server.key https://localhost:8080/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / DHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=localhost; C=US
*  start date: Oct 15 22:41:35 2016 GMT
*  expire date: Oct 15 22:41:35 2017 GMT
*  issuer: CN=localhost; C=US
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.50.3
> Accept: */*
>
< HTTP/1.1 101 Switching Protocols
< Connection: Upgrade
< Upgrade: h2
<
```

I added the certificate exception to Chrome, and to the Keychain (OSX). But the browser hangs when making the request.

I'll try using the code from upgrade_server.rb.

**Comment by kenichi** [comment]
is `Upgrade: h2` a thing? i thought upgrades were h2c _only_?

also, to make sure your curl supports http2, check --version, and then use the --http2 option on your command:

```
$ brew install curl --with-nghttp2

...

$ /usr/local/Cellar/curl/7.50.3/bin/curl --version
curl 7.50.3 (x86_64-apple-darwin16.0.0) libcurl/7.50.3 OpenSSL/1.0.2j zlib/1.2.8 c-ares/1.12.0 libidn/1.33 nghttp2/1.15.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets Metalink

# NOTE - HTTP2 in the Features list there ----------------------------------------------------^^

$ /usr/local/Cellar/curl/7.50.3/bin/curl --http2 -vk https://vux.nakamura.io:4430/
*   Trying 192.155.84.174...
* TCP_NODELAY set
* Connected to vux.nakamura.io (192.155.84.174) port 4430 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / DHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=nakamura.io
*  start date: Sep  4 16:44:00 2016 GMT
*  expire date: Dec  3 16:44:00 2016 GMT
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fadb2801c00)
> GET / HTTP/1.1
> Host: vux.nakamura.io:4430
> User-Agent: curl/7.50.3
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< content-length: 13
< content-type: text/plain
< 
hello world!
* Curl_http_done: called premature == 0
* Connection #0 to host vux.nakamura.io left intact
```

note: the above is *not* an h2c upgrade. i'd have to use `http://` for curl to do that and run my server without SSL. (see https://github.com/kenichi/reel/blob/h2/lib/reel/h2/server.rb#L24-L59)

**Comment by georgeu2000** [comment]
OK, thanks for all the help. Yes, I forgot the `--http2` flag on curl. And yes, I have 7.50.3 which supports it. 

curl with http2 seems to be working. Getting closer...

```
curl -vk --http2 --cert lib/keys/sehttps://localhost:8080//server.key h
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / DHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=localhost; C=US
*  start date: Oct 15 22:41:35 2016 GMT
*  expire date: Oct 15 22:41:35 2017 GMT
*  issuer: CN=localhost; C=US
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.50.3
> Accept: */*
>
< HTTP/1.1 101 Switching Protocols
< Connection: Upgrade
< Upgrade: h2
<
d	_�I|����message from server
* TLSv1.2 (IN), TLS alert, Client hello (1):
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

**Pull request merged**
